### ISSUE TITLE
106: Field 'type' on type 'Device' is of incorrect type. Expected: string, Actual: undefined

### ISSUE THREAD

**Issue by calloncampbell** [khaines/angular-applicationinsights#35] opened 2016-01-26 21:53 UTC
From time to time I see the following error in the browser console. When it happens, all tracking stops. It's not consistent when it happens.

dc.services.visualstudio.com/v2/track:1 POST https://dc.services.visualstudio.com/v2/track 400 (106: Field 'type' on type 'Device' is of incorrect type. Expected: string, Actual: undefined)

**Comment by calloncampbell** [comment] 2016-01-27 15:31
Here is the header/response data...

-- Request Headers:
POST /v2/track HTTP/1.1
Host: dc.services.visualstudio.com
Connection: keep-alive
Content-Length: 548
Accept: application/json
Origin: http://dev.calltelligence.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Content-Type: application/json
Referer: http://dev.calltelligence.com/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

-- Response Headers:
HTTP/1.1 400 106: Field 'type' on type 'Device' is of incorrect type. Expected: string, Actual: undefined
Content-Length: 182
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.5
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Name, Content-Type, Accept
Access-Control-Allow-Origin: *
X-Powered-By: ASP.NET
Date: Wed, 27 Jan 2016 15:27:21 GMT

-- Response:
{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"106: Field 'type' on type 'Device' is of incorrect type. Expected: string, Actual: undefined"}]}

**Comment by kowsheek** [comment] 2016-01-27 19:42
I'm getting this as well.

**Comment by calloncampbell** [comment] 2016-01-27 20:37
Maybe something changed with Application Insights service itself. 

I tried updating my local source JavaScript file (0.2.7) and added 'type: "PC",' for the device section. That error goes away and I then get a similar error for the user. Updating that with a 'type' makes that error go away and then I get a pageview error. I'm no familiar enough with this library to debug it further than that.

**Comment by kowsheek** [comment] 2016-01-27 21:30
Yes, it seems the upgraded version of the Application Insights added a bunch of new things, which are cool. Time to upgrade our stuff! I'll try to get a PR in over the weekend with fixes. Take a look and see if there are things you can PR with @calloncampbell: https://github.com/Microsoft/ApplicationInsights-JS/tree/master/JavaScript/JavaScriptSDK

**Comment by MaxShehovtsov** [comment] 2016-01-27 23:11
Hi Folks - for your information:
In order for the telemetry to show up on *browser* blade (i.e. to be treated as browser telemetry) it has to have device type = "Browser". JS SDK sets it by default.
If you want your telemetry to show up on *server* blades (like server performance, or failures) it has to have device type "PC".

**Comment by ersommer** [comment] 2016-01-29 00:01
From what I've heard, they recently moved to some new server-side code which has stricter schema validators. Adding the 2 fields (device.type and user.type) to the data sent seems to be easy. Would you just want a PR for that? If so, I can probably get that done today.

The official JavaScript SDK looks like it's using a different schema when it sends the data, perhaps it's a newer version. Is there anything tracking the work to upgrade to that schema?

**Comment by MaxShehovtsov** [comment] 2016-01-29 00:05
Currently JS SDK uses the most recent production schema. And recently there was a change in UI (and hence reflected in JSSDK) that 'browser' blade (the one that shows JS SDK telemetry) will only show telemetry wiith device.type = "Browser".

**Comment by khaines** [comment] 2016-01-29 04:06
If someone has time to update the code to the latest schemas, then a PR will be quickly approved.

**Comment by khaines** [comment] 2016-01-29 04:21
Seems rather annoying that they change the data contract without rev'ing the version number, but seems the simple 'min solution' is to add the two fields the endpoint is complaining about.

**Comment by khaines** [comment] 2016-01-29 04:55
correction, it looks like the inner version numbers were rev'd, but they broke back compat with the previous version. There is more than just adding two fields in this change to get it updated. 

I no longer use Application Insights, so if there is someone wanting to own this repository and give it it the attention it needs, please msg me. I'll review and approve any PR's for the repository also, but it would be best for someone actually using the system to own the repository

**Comment by ersommer** [comment] 2016-01-29 05:09
I talked with the a member of the App Insights team, and they confirmed they recently enabled additional schema validation on their side, which is why it all of a sudden stopped working. Additionally, this module uses v1 of the schema which will eventually be unsupported. There's a v2 of the schema (which the JS SDK uses) that is significantly different.

I've added the device.type and user.type fields to a local copy of this module, and it almost worked. I had to change the type (I believe it was PageviewData to PageViewData). I can work on getting a PR for these changes out tomorrow, but it would be good to have something tracking moving to the v2 schema.

**Comment by C-E-Rios** [comment] 2016-01-29 16:46
@ersommer thanks for that. After applying your fixes, I then started to see the below when an exception is thrown. 

>  Field 'typeName' on type 'ExceptionDetails' is of incorrect type. Expected: string, Actual: undefined

**Comment by ersommer** [comment] 2016-01-29 23:37
@C-E-Rios It appears that the object passed into `trackException` must have values for `name` and `message`. Without those, the validation fails. The `trackException` method sets `typeName` to `exception.name` when it's building the data to send, which is actually what the App Insights server expects.

I've tested the other methods, and they all seem to be working. @Sin360 has a PR out for adding the missing types. I'll get a PR out shortly for changing the capitalization of PageviewData so the server will accept it. With those changes, I think everything should be working again.

**Comment by khaines** [comment] 2016-01-30 01:47
Prematurely closed the issue via tooling.

Thanks folks for submitting the PR's. I've merged them and kicked off the release tools to push the update into npm and nuget.

I'll leave this issue open for the next while for anyone having a similar issue on 0.2.8 to comment on.

**Comment by calloncampbell** [comment] 2016-02-02 20:11
I've upgraded to v0.2.8 and the issue seems to be resolved. Thanks for the quick turn around on this. Very much appreciate it.

**Closed** 2016-02-04 22:38 UTC

**Comment by wk001** [comment] 2016-05-11 12:23
I'm experiencing a similar issue with v0.2.8 when handling an error with the exceptionHandler decorator:

angular-applicationinsights.js:628 
POST https://dc.services.visualstudio.com/v2/track 400 (109: Field 'typeName' on type 'ExceptionDetails' is required but missing or empty. Expected: string, Actual: undefined)
